/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.zz_proyecto1;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Juan Jimenez
 */
public class Ventana extends javax.swing.JFrame {
        ArrayList<Personaje> zombies;
        ArrayList<Personaje> defensas;
    public Ventana() {
        
        zombies = new ArrayList<Personaje>();
        defensas = new ArrayList<Personaje>();
        cargaImagen("menu.jpg");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlZombies = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaZombiesCreados = new javax.swing.JTextArea();
        lblZombiesCreados = new javax.swing.JLabel();
        pnlDefensas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaDefensasCreadas = new javax.swing.JTextArea();
        lblDefensasCreadas = new javax.swing.JLabel();
        sldEleccion = new javax.swing.JSlider();
        lblElecionDefensa = new javax.swing.JLabel();
        lblMenu1 = new javax.swing.JLabel();
        lblElecionZombie = new javax.swing.JLabel();
        pnlDefensas1 = new javax.swing.JPanel();
        btnCrearDef = new javax.swing.JButton();
        lblNombreDef = new javax.swing.JLabel();
        txfNombreDef = new javax.swing.JTextField();
        lblVidaDef = new javax.swing.JLabel();
        txfVidaDef = new javax.swing.JTextField();
        lblDanoDef = new javax.swing.JLabel();
        txfGolpesDef = new javax.swing.JTextField();
        lblCamposDef = new javax.swing.JLabel();
        txfCamposDef = new javax.swing.JTextField();
        lblLvlAparicionDef = new javax.swing.JLabel();
        txfLvlApariciónDef = new javax.swing.JTextField();
        cbxDefensas = new javax.swing.JComboBox<>();
        txfLvlRangoDef = new javax.swing.JTextField();
        txfImagen1Def = new javax.swing.JTextField();
        lblLvlRangoDef = new javax.swing.JLabel();
        lblImagenDef = new javax.swing.JLabel();
        pnlZombies1 = new javax.swing.JPanel();
        txfLvlApariciónZom = new javax.swing.JTextField();
        txfNombreZom = new javax.swing.JTextField();
        txfVidaZom = new javax.swing.JTextField();
        txfGolpesZom = new javax.swing.JTextField();
        txfCamposZom = new javax.swing.JTextField();
        lblLvlAparicionZom = new javax.swing.JLabel();
        lblVidaZom = new javax.swing.JLabel();
        lblDanoZom = new javax.swing.JLabel();
        lblCamposZom = new javax.swing.JLabel();
        cbxZombies = new javax.swing.JComboBox<>();
        lblNombreZom1 = new javax.swing.JLabel();
        btnCrearZom = new javax.swing.JButton();
        txfLvlRangoZom = new javax.swing.JTextField();
        txfImagen1Zom = new javax.swing.JTextField();
        lblLvlRangoZom = new javax.swing.JLabel();
        lblImagenZom = new javax.swing.JLabel();
        btnCrearPartida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txfNomPartida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Configuracion de Juego");
        setMinimumSize(new java.awt.Dimension(900, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlZombies.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));

        txaZombiesCreados.setEditable(false);
        txaZombiesCreados.setColumns(20);
        txaZombiesCreados.setRows(5);
        jScrollPane2.setViewportView(txaZombiesCreados);

        lblZombiesCreados.setText("Zombies Creados");

        javax.swing.GroupLayout pnlZombiesLayout = new javax.swing.GroupLayout(pnlZombies);
        pnlZombies.setLayout(pnlZombiesLayout);
        pnlZombiesLayout.setHorizontalGroup(
            pnlZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(pnlZombiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblZombiesCreados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlZombiesLayout.setVerticalGroup(
            pnlZombiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlZombiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblZombiesCreados)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );

        getContentPane().add(pnlZombies, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 130, 330, 220));

        pnlDefensas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));

        txaDefensasCreadas.setEditable(false);
        txaDefensasCreadas.setColumns(20);
        txaDefensasCreadas.setRows(5);
        jScrollPane1.setViewportView(txaDefensasCreadas);

        lblDefensasCreadas.setText("Defensas Creadas");

        javax.swing.GroupLayout pnlDefensasLayout = new javax.swing.GroupLayout(pnlDefensas);
        pnlDefensas.setLayout(pnlDefensasLayout);
        pnlDefensasLayout.setHorizontalGroup(
            pnlDefensasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
            .addGroup(pnlDefensasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDefensasCreadas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlDefensasLayout.setVerticalGroup(
            pnlDefensasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDefensasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDefensasCreadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(pnlDefensas, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 330, 210));

        sldEleccion.setOpaque(false);
        sldEleccion.setMaximum(2);
        sldEleccion.setValue(1);
        sldEleccion.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sldEleccionStateChanged(evt);
            }
        });
        sldEleccion.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                sldEleccionComponentHidden(evt);
            }
        });
        getContentPane().add(sldEleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        lblElecionDefensa.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        lblElecionDefensa.setForeground(new java.awt.Color(0, 51, 255));
        lblElecionDefensa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblElecionDefensa.setText("DEFENSA");
        lblElecionDefensa.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblElecionDefensaComponentHidden(evt);
            }
        });
        getContentPane().add(lblElecionDefensa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        lblMenu1.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        lblMenu1.setForeground(new java.awt.Color(153, 0, 0));
        lblMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenu1.setText("Bienvenido al menu de Juego!");
        getContentPane().add(lblMenu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        lblElecionZombie.setFont(new java.awt.Font("Chiller", 1, 36)); // NOI18N
        lblElecionZombie.setForeground(new java.awt.Color(153, 0, 0));
        lblElecionZombie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblElecionZombie.setText("ZOMBIE");
        lblElecionZombie.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                lblElecionZombieComponentHidden(evt);
            }
        });
        getContentPane().add(lblElecionZombie, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        pnlDefensas1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 3));
        pnlDefensas1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCrearDef.setText("Crear Defensa");
        btnCrearDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearDefActionPerformed(evt);
            }
        });
        pnlDefensas1.add(btnCrearDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        lblNombreDef.setText("Nombre");
        pnlDefensas1.add(lblNombreDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txfNombreDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreDefActionPerformed(evt);
            }
        });
        pnlDefensas1.add(txfNombreDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 197, -1));

        lblVidaDef.setText("Vida");
        pnlDefensas1.add(lblVidaDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txfVidaDef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });
        txfVidaDef.setText("100");
        txfVidaDef.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfVidaDefMouseClicked(evt);
            }
        });
        txfVidaDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfVidaDefActionPerformed(evt);
            }
        });
        pnlDefensas1.add(txfVidaDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 197, -1));

        lblDanoDef.setText("Daño");
        pnlDefensas1.add(lblDanoDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txfGolpesDef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });
        txfGolpesDef.setText("2");
        txfGolpesDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfGolpesDefActionPerformed(evt);
            }
        });
        pnlDefensas1.add(txfGolpesDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 197, -1));

        lblCamposDef.setText("Campo");
        pnlDefensas1.add(lblCamposDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        txfCamposDef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });
        txfCamposDef.setText("2");
        txfCamposDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCamposDefActionPerformed(evt);
            }
        });
        pnlDefensas1.add(txfCamposDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 197, -1));

        lblLvlAparicionDef.setText("Lvl Aparición");
        pnlDefensas1.add(lblLvlAparicionDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txfLvlApariciónDef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });
        txfLvlApariciónDef.setText("0");
        txfLvlApariciónDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfLvlApariciónDefActionPerformed(evt);
            }
        });
        pnlDefensas1.add(txfLvlApariciónDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 197, -1));

        cbxDefensas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De contacto", "Mediano alcance", "Aereo", "Impacto", "Ataque multiple", "Bloques" }));
        cbxDefensas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDefensasActionPerformed(evt);
            }
        });
        pnlDefensas1.add(cbxDefensas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 197, -1));

        txfLvlRangoDef.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });
        txfLvlRangoDef.setText("3");
        txfLvlRangoDef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfLvlRangoDefActionPerformed(evt);
            }
        });
        pnlDefensas1.add(txfLvlRangoDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 197, -1));

        txfImagen1Def.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfImagen1DefActionPerformed(evt);
            }
        });
        pnlDefensas1.add(txfImagen1Def, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 197, -1));

        lblLvlRangoDef.setText("Rango");
        pnlDefensas1.add(lblLvlRangoDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        lblImagenDef.setText("Imagenes (Nombre imagen)");
        pnlDefensas1.add(lblImagenDef, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        getContentPane().add(pnlDefensas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 215, 450));

        pnlZombies1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
        pnlZombies1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txfLvlApariciónZom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });
        txfLvlApariciónZom.setText("0");
        txfLvlApariciónZom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfLvlApariciónZomActionPerformed(evt);
            }
        });
        pnlZombies1.add(txfLvlApariciónZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 197, -1));

        txfNombreZom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNombreZomActionPerformed(evt);
            }
        });
        pnlZombies1.add(txfNombreZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 197, -1));

        txfVidaZom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });
        txfVidaZom.setText("100");
        txfVidaZom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txfVidaZomMouseClicked(evt);
            }
        });
        txfVidaZom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfVidaZomActionPerformed(evt);
            }
        });
        pnlZombies1.add(txfVidaZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 197, -1));

        txfGolpesZom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });
        txfGolpesZom.setText("1");
        txfGolpesZom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfGolpesZomActionPerformed(evt);
            }
        });
        pnlZombies1.add(txfGolpesZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 197, -1));

        txfCamposZom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });
        txfCamposZom.setText("2");
        txfCamposZom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfCamposZomActionPerformed(evt);
            }
        });
        pnlZombies1.add(txfCamposZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 197, -1));

        lblLvlAparicionZom.setText("Lvl Aparición");
        pnlZombies1.add(lblLvlAparicionZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lblVidaZom.setText("Vida");
        pnlZombies1.add(lblVidaZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        lblDanoZom.setText("Daño");
        pnlZombies1.add(lblDanoZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        lblCamposZom.setText("Campo");
        pnlZombies1.add(lblCamposZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        cbxZombies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "De contacto", "Aereo", "Mediano alcance", "Choque" }));
        cbxZombies.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxZombiesActionPerformed(evt);
            }
        });
        pnlZombies1.add(cbxZombies, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 197, -1));

        lblNombreZom1.setText("Nombre");
        pnlZombies1.add(lblNombreZom1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        btnCrearZom.setText("Crear Zombie");
        btnCrearZom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearZomActionPerformed(evt);
            }
        });
        pnlZombies1.add(btnCrearZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        txfLvlRangoZom.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                char c = evt.getKeyChar();
                if (!Character.isDigit(c)) {
                    evt.consume();
                }
            }
        });
        txfLvlRangoZom.setText("3");
        txfLvlRangoZom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfLvlRangoZomActionPerformed(evt);
            }
        });
        pnlZombies1.add(txfLvlRangoZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 197, -1));

        txfImagen1Zom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfImagen1ZomActionPerformed(evt);
            }
        });
        pnlZombies1.add(txfImagen1Zom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 197, -1));

        lblLvlRangoZom.setText("Rango");
        pnlZombies1.add(lblLvlRangoZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        lblImagenZom.setText("Imagenes (Nombre imagen)");
        pnlZombies1.add(lblImagenZom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));

        getContentPane().add(pnlZombies1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 216, 450));

        btnCrearPartida.setBackground(java.awt.Color.gray);
        btnCrearPartida.setFont(new java.awt.Font("Chiller", 1, 24)); // NOI18N
        btnCrearPartida.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearPartida.setText("Crear Partida");
        btnCrearPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCrearPartidaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearPartidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCrearPartidaMouseExited(evt);
            }
        });
        btnCrearPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 580, -1, -1));

        jLabel1.setFont(new java.awt.Font("Chiller", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Nombre de la Partida:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, -1, -1));

        txfNomPartida.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 3));
        txfNomPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfNomPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(txfNomPartida, new org.netbeans.lib.awtextra.AbsoluteConstraints(681, 92, 170, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxDefensasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDefensasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDefensasActionPerformed

    private void txfCamposZomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCamposZomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCamposZomActionPerformed

    private void lblElecionDefensaComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblElecionDefensaComponentHidden
        
    }//GEN-LAST:event_lblElecionDefensaComponentHidden

    private void sldEleccionComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_sldEleccionComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_sldEleccionComponentHidden

    private void sldEleccionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sldEleccionStateChanged
        if (sldEleccion.getValue() == 1){
            pnlDefensas1.setVisible(false);
            pnlZombies1.setVisible(false);
        } else if(sldEleccion.getValue() == 0){
            pnlDefensas1.setVisible(true);
            pnlZombies1.setVisible(false);
        }else{
            pnlDefensas1.setVisible(false);
            pnlZombies1.setVisible(true);
        }
        
    }//GEN-LAST:event_sldEleccionStateChanged

    private void lblElecionZombieComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_lblElecionZombieComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_lblElecionZombieComponentHidden

    private void cbxZombiesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxZombiesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxZombiesActionPerformed

    private void txfVidaZomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfVidaZomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txfVidaZomMouseClicked

    private void btnCrearDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearDefActionPerformed
        String nombreD = txfNombreDef.getText().trim();
        String vida = txfVidaDef.getText().trim();
        String golpes = txfGolpesDef.getText().trim();
        String campos = txfCamposDef.getText().trim();
        String apari = txfLvlApariciónDef.getText().trim();
        String comboD = (String) cbxDefensas.getSelectedItem();
        String rango = txfLvlRangoDef.getText().trim();
        String img1Def = txfImagen1Def.getText().trim();
        int vidas = Integer.parseInt(vida);
        int golpe = Integer.parseInt(golpes);
        int campo = Integer.parseInt(campos);
        int aparis = Integer.parseInt(apari);
        int rangos = Integer.parseInt(rango);
        txaDefensasCreadas.append(nombreD + " " +comboD + " con vida: " + vidas +"\n");
        if(comboD == "De contacto" || comboD == "Aereos"){
            agregarPersonaLista(nombreD, img1Def, "", vidas, golpe, 0, campo, aparis, comboD, 1, 1);
        }else if(comboD == "Impacto"){
            agregarPersonaLista(nombreD, img1Def, "", vidas, golpe, 0, campo, aparis, comboD, 1, 1);
        }else if(comboD == "Bloques"){
            agregarPersonaLista(nombreD, img1Def, "", vidas, 0, 0, campo, aparis, comboD, 0, 1);
        }else if(comboD == "Mediano alcance"){
            agregarPersonaLista(nombreD, img1Def, "", vidas, golpe, 0, campo, aparis, comboD, rangos, 1);
        }else{
            agregarPersonaLista(nombreD, img1Def, "", vidas, golpe, 0, campo, aparis, comboD, rangos, 1);
        }
        txfImagen1Def.setText("");
        txfNombreDef.setText(""); 
        txfVidaDef.setText("100"); 
        txfGolpesDef.setText("1"); 
        txfCamposDef.setText("2");
        txfLvlRangoDef.setText("2");
        txfLvlApariciónDef.setText("0");       
    }//GEN-LAST:event_btnCrearDefActionPerformed

    private void txfLvlApariciónZomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLvlApariciónZomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLvlApariciónZomActionPerformed

    private void txfNombreZomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreZomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreZomActionPerformed

    private void txfVidaZomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfVidaZomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfVidaZomActionPerformed

    private void txfGolpesZomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfGolpesZomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGolpesZomActionPerformed

    private void txfNombreDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNombreDefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNombreDefActionPerformed

    private void txfVidaDefMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txfVidaDefMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txfVidaDefMouseClicked

    private void txfVidaDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfVidaDefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfVidaDefActionPerformed

    private void txfGolpesDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfGolpesDefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGolpesDefActionPerformed

    private void txfCamposDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfCamposDefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfCamposDefActionPerformed

    private void txfLvlApariciónDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLvlApariciónDefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLvlApariciónDefActionPerformed

    private void btnCrearZomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearZomActionPerformed
        String nombreZ = txfNombreZom.getText().trim();
        String vida = txfVidaZom.getText().trim();
        String golpes = txfGolpesZom.getText().trim();
        String campos = txfCamposZom.getText().trim();
        String apari = txfLvlApariciónZom.getText().trim();
        String comboZ = (String) cbxZombies.getSelectedItem();
        String rango = txfLvlRangoZom.getText().trim();
        String img1Zom = txfImagen1Zom.getText().trim();
        int vidas = Integer.parseInt(vida);
        int golpe = Integer.parseInt(golpes);
        int campo = Integer.parseInt(campos);
        int aparis = Integer.parseInt(apari);
        int rangos = Integer.parseInt(rango);
        txaZombiesCreados.append(nombreZ + " " +comboZ + " con vida: " + vidas +"\n");
        if (comboZ == "Aereo" || comboZ == "De contacto"){
             agregarPersonaLista(nombreZ, img1Zom, "", vidas, golpe, 0, campo, aparis, comboZ, 1,0);
        }else if(comboZ == "Choque"){
            agregarPersonaLista(nombreZ, img1Zom, "", vidas, golpe, 0, campo, aparis, comboZ, 1,0);
        }else{
            agregarPersonaLista(nombreZ, img1Zom, "", vidas, golpe, 0, campo, aparis, comboZ, rangos,0);
        }
        
        
        txfImagen1Zom.setText("");
        txfNombreZom.setText(""); 
        txfVidaZom.setText("100"); 
        txfGolpesZom.setText("1"); 
        txfCamposZom.setText("2"); 
        txfLvlRangoZom.setText("2");
        txfLvlApariciónZom.setText("0");  
    }//GEN-LAST:event_btnCrearZomActionPerformed

    private void btnCrearPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPartidaActionPerformed
        if (txfNomPartida.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Por favor, llene el campo de nombre de partida", "Campo Vacío", JOptionPane.WARNING_MESSAGE);
        }else{
            guardarPartida();
            JOptionPane.showMessageDialog(null, "Los ejercitos se guardaron correctamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            txaDefensasCreadas.setText("");
            txaZombiesCreados.setText("");
            txfNomPartida.setText("");
            zombies.clear();
            defensas.clear();
        }
                       
    }//GEN-LAST:event_btnCrearPartidaActionPerformed

    private void btnCrearPartidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPartidaMouseEntered
        btnCrearPartida.setBackground(Color.RED);
    }//GEN-LAST:event_btnCrearPartidaMouseEntered

    private void btnCrearPartidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPartidaMouseExited
        btnCrearPartida.setBackground(Color.GRAY);
    }//GEN-LAST:event_btnCrearPartidaMouseExited

    private void txfLvlRangoDefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLvlRangoDefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLvlRangoDefActionPerformed

    private void txfImagen1DefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfImagen1DefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfImagen1DefActionPerformed

    private void txfLvlRangoZomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfLvlRangoZomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfLvlRangoZomActionPerformed

    private void txfImagen1ZomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfImagen1ZomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfImagen1ZomActionPerformed

    private void btnCrearPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearPartidaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearPartidaMouseClicked

    private void txfNomPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfNomPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfNomPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana frame = new Ventana();
                frame.setVisible(true);
            }    
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearDef;
    private javax.swing.JButton btnCrearPartida;
    private javax.swing.JButton btnCrearZom;
    private javax.swing.JComboBox<String> cbxDefensas;
    private javax.swing.JComboBox<String> cbxZombies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblCamposDef;
    private javax.swing.JLabel lblCamposZom;
    private javax.swing.JLabel lblDanoDef;
    private javax.swing.JLabel lblDanoZom;
    private javax.swing.JLabel lblDefensasCreadas;
    private javax.swing.JLabel lblElecionDefensa;
    private javax.swing.JLabel lblElecionZombie;
    private javax.swing.JLabel lblImagenDef;
    private javax.swing.JLabel lblImagenZom;
    private javax.swing.JLabel lblLvlAparicionDef;
    private javax.swing.JLabel lblLvlAparicionZom;
    private javax.swing.JLabel lblLvlRangoDef;
    private javax.swing.JLabel lblLvlRangoZom;
    private javax.swing.JLabel lblMenu1;
    private javax.swing.JLabel lblNombreDef;
    private javax.swing.JLabel lblNombreZom1;
    private javax.swing.JLabel lblVidaDef;
    private javax.swing.JLabel lblVidaZom;
    private javax.swing.JLabel lblZombiesCreados;
    private javax.swing.JPanel pnlDefensas;
    private javax.swing.JPanel pnlDefensas1;
    private javax.swing.JPanel pnlZombies;
    private javax.swing.JPanel pnlZombies1;
    private javax.swing.JSlider sldEleccion;
    private javax.swing.JTextArea txaDefensasCreadas;
    private javax.swing.JTextArea txaZombiesCreados;
    private javax.swing.JTextField txfCamposDef;
    private javax.swing.JTextField txfCamposZom;
    private javax.swing.JTextField txfGolpesDef;
    private javax.swing.JTextField txfGolpesZom;
    private javax.swing.JTextField txfImagen1Def;
    private javax.swing.JTextField txfImagen1Zom;
    private javax.swing.JTextField txfLvlApariciónDef;
    private javax.swing.JTextField txfLvlApariciónZom;
    private javax.swing.JTextField txfLvlRangoDef;
    private javax.swing.JTextField txfLvlRangoZom;
    private javax.swing.JTextField txfNomPartida;
    private javax.swing.JTextField txfNombreDef;
    private javax.swing.JTextField txfNombreZom;
    private javax.swing.JTextField txfVidaDef;
    private javax.swing.JTextField txfVidaZom;
    // End of variables declaration//GEN-END:variables

    public void cargaImagen(String imagen){
//        if ("menu.jpg".equals(imagen))
//        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        try{
            BufferedImage backgroundImage = ImageIO.read(new File("your image direction"));
            A_imagen backgroundPanel = new A_imagen(backgroundImage);
            setContentPane(backgroundPanel);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    public void agregarPersonaLista(String nombre, String img1, String img2, int vida, int golpes, int nivel, int campos, int aparicion, String Combo, int rango, int bandera){
        if (defensas.isEmpty()){
            defensas.add(new Personaje("Partida","0", "0", 2000, 0, 0, 0, 0, "0", 0));
            defensas.add(new Personaje("Reliquia","reliquia.png", "", 300, 0, 0, 0, 0, "reliquia", 0));
        }
        if (bandera == 0){
            zombies.add(new Personaje(nombre,img1, "", vida, golpes, nivel, campos, aparicion, Combo, rango));
        }else if (bandera == 1){
            defensas.add(new Personaje(nombre,img1, "", vida, golpes, nivel, campos, aparicion, Combo, rango));
        }        
    }
    
    public void guardarPartida(){
        String partida = txfNomPartida.getText();
        FileManager.writeObject(defensas, partida+"=def.ser");
        FileManager.writeObject(zombies, partida+"=Zom.ser"); 
    }
}
