/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Robo_Zombie;

import com.mycompany.zz_proyecto1.A_imagen;
import com.mycompany.zz_proyecto1.FileManager;
import com.mycompany.zz_proyecto1.Personaje;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author Juan Jimenez
 */
public class CargarPartida extends javax.swing.JFrame {
        ArrayList<Personaje> listaDefensas;
        ArrayList<Personaje> listaZombie;
        
    /**
     * Creates new form CargarPartida
     */
    public CargarPartida(){
        listaDefensas = new ArrayList<Personaje>();
        listaZombie = new ArrayList<Personaje>();
        cargaImagen("defensa.jpg");
        initComponents();
        jScrollPane1.setHorizontalScrollBarPolicy(jScrollPane1.HORIZONTAL_SCROLLBAR_NEVER);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstCargarPartida = new javax.swing.JList<>();
        btnSeleccionarPartida = new javax.swing.JButton();
        lblMenuPartida = new javax.swing.JLabel();
        txfTraerPartida = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Seleccione Partida");
        setMinimumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        lstCargarPartida.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        lstCargarPartida.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = cargarNomPartida();
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstCargarPartida.setPreferredSize(new java.awt.Dimension(400, 400));
        jScrollPane1.setViewportView(lstCargarPartida);
        lstCargarPartida.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(77, 110, 196, 140);

        btnSeleccionarPartida.setText("Seleccionar");
        btnSeleccionarPartida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSeleccionarPartidaMouseClicked(evt);
            }
        });
        btnSeleccionarPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(btnSeleccionarPartida);
        btnSeleccionarPartida.setBounds(120, 270, 110, 23);

        lblMenuPartida.setFont(new java.awt.Font("Chiller", 3, 24)); // NOI18N
        lblMenuPartida.setForeground(new java.awt.Color(204, 204, 0));
        lblMenuPartida.setText("Escoger partida");
        getContentPane().add(lblMenuPartida);
        lblMenuPartida.setBounds(109, 48, 118, 29);

        txfTraerPartida.setVisible(false);
        txfTraerPartida.setEditable(false);
        txfTraerPartida.setForeground(new java.awt.Color(255, 255, 255));
        txfTraerPartida.setBorder(null);
        txfTraerPartida.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txfTraerPartidaCaretUpdate(evt);
            }
        });
        txfTraerPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfTraerPartidaActionPerformed(evt);
            }
        });
        getContentPane().add(txfTraerPartida);
        txfTraerPartida.setBounds(140, 300, 71, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarPartidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSeleccionarPartidaMouseClicked
        if (lstCargarPartida.isSelectionEmpty()){//Si no tiene nada seleccionado, ponga un mensaje de error
            JOptionPane.showMessageDialog(null, "Por favor, seleccione una partida", "Seleccionar Partida", JOptionPane.WARNING_MESSAGE);
        }else{
                txfTraerPartida.setText(lstCargarPartida.getSelectedValue());
                JuegoGrafico frame = new JuegoGrafico();//pasar aqui las listas y en la Juego grafico hacerlos de su respectiva clase
                frame.setVisible(true);
                this.dispose();
                }
    }//GEN-LAST:event_btnSeleccionarPartidaMouseClicked

    private void btnSeleccionarPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarPartidaActionPerformed
        
    }//GEN-LAST:event_btnSeleccionarPartidaActionPerformed

    private void txfTraerPartidaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txfTraerPartidaCaretUpdate
        Temporal tm = new Temporal();
        tm.setTexto(lstCargarPartida.getSelectedValue());
    }//GEN-LAST:event_txfTraerPartidaCaretUpdate

    private void txfTraerPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfTraerPartidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfTraerPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CargarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CargarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CargarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CargarPartida.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CargarPartida cPartida = new CargarPartida();
                cPartida.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSeleccionarPartida;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMenuPartida;
    private javax.swing.JList<String> lstCargarPartida;
    private javax.swing.JTextField txfTraerPartida;
    // End of variables declaration//GEN-END:variables

    public String[] cargarNomPartida(){
        String rutaDirectorio = "your file.ser direction";
        ArrayList<String> archivosSer;
        archivosSer = listarArchivosSer(rutaDirectorio);
        int i =0;
        String[] nArchivo;
        ArrayList<String> listaArchivos = new ArrayList<>();
        for (String nombreArchivo : archivosSer) {
            if (i%2==0){
                nArchivo = nombreArchivo.split("=");
                listaArchivos.add(nArchivo[0]);
            }
            i++;
        }
        String[] Partidas = listaArchivos.toArray(new String[0]);
        return Partidas;
    }
    
    public ArrayList<String> listarArchivosSer(String rutaDirectorio) {
        ArrayList<String> archivosSer = new ArrayList<>();

        File directorio = new File(rutaDirectorio);
        File[] archivos = directorio.listFiles();

        if (archivos != null) {
            for (File archivo : archivos) {
                if (archivo.isFile() && archivo.getName().endsWith(".ser")) {
                    archivosSer.add(archivo.getName());
                }
            }
        }
        return archivosSer;
    }
    
    public void cargaImagen(String imagen){
        try{
            BufferedImage backgroundImage = ImageIO.read(new File("your image direction"));
            A_imagen backgroundPanel = new A_imagen(backgroundImage);
            setContentPane(backgroundPanel);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
}
